PillGood_backend/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    # path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('kakao/login/', views.kakao_login, name='kakao_login'),
    path('naver/login/', views.naver_login, name='naver_login'),

    path('google/callback/', views.google_callback, name='google_callback'),
    path('check-google-link/', views.check_google_link),
    path('google/unlink/', views.google_unlink),
    
    path('profile/' , views.user_profile, name='user_profile'),
    path('user-delete/', views.user_delete, name='user_delete'),
    path('allergies/', views.allergy_list, name='allergy_list'),
    # 자체 회원 비밀번호 변경
    path('change-password/', views.change_password, name='change_password'),
    # 아이디 찾기
    path('find-id/', views.find_id, name='find_id'),
    # 구글 SMTP 활용해서 , 비밀번호 찾기
    path('password-reset-verify/', views.password_reset_verify, name='password_reset_verify'),
    path('password-reset-send/', views.password_reset_send),
    path('password-reset-confirm/', views.password_reset_confirm, name='password_reset_confirm'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pills/', include('pills.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pills/urls.py
from django.urls import path
from . import views


app_name = "pills"
urlpatterns = [
    # 구글 캘린더
    path('google-calendar/', views.register_google_calendar, name='google_calendar'),
    
    path("", views.index, name="index"),
    path("<int:pill_pk>/", views.detail, name="detail"),

    # 영양제함 담기
    path('<int:pill_pk>/toggle/', views.toggle_pill, name='toggle_pill'),

    # 🚩 내 영양제함 목록 불러오기 (마이페이지용)
    path('my-pills/', views.my_pills, name='my_pills'),

    # 사용자의 영양제함에 들어있는지 확인
    path('<int:pill_pk>/is-enrolled/', views.check_pill_enrollment, name='check_enrollment'),

    # 사용자 커스텀 영양제
    path('custom-pills/', views.custom_pill_list, name='custom_pill_list'),

    # 사용자 커스텀 영양제 삭제
    path('custom-pills/<int:pk>/', views.custom_pill_detail, name='custom_pill_detail'),

    # 사용자 커스텀 영양제에 성분 작성 할 때, 목록 띄우기
    path('all-ingredients/', views.all_ingredients_list, name='all_ingredients_list'),

    # 챗봇 서비스 url
    path('chatbot/', views.chatbot_view, name='chatbot_view'),

    # 아래는 vue랑 django 연결해주는 쓰레드 목록 조회 api 새로 작성
    path("<int:pill_pk>/threads/", views.thread_list, name="thread_list"),

    # 기존의 있는 thraed/create 대신, 밑에 있는 thread_create_api로 활용
    # path('<int:pill_pk>/thread/create', views.thread_create, name='thread_create'),
    path('<int:pill_pk>/thread/create/', views.thread_create_api, name='thread_create_api'),
    
    path('categories/', views.category_list, name='category_list'),
    # path("filter-category/", views.filter_category, name="filter_category"),
    # [추가] 맞춤 추천 메인 (모든 카테고리 조회)
    path('categories/', views.category_list),
    
    # [추가] 특정 카테고리의 성분 리스트 조회
    path('categories/<int:category_id>/', views.category_detail),
    
    # [추가] 성분 상세 정보 조회
    path('substances/<int:substance_id>/', views.substance_detail),
    
    # [추가] 성분별 영양제 리스트 (필터링 포함)
    path('substances/<int:substance_id>/pills/', views.substance_pills),
    path(
        '<int:pill_pk>/thread/<int:thread_pk>/',
        views.thread_detail,
        name='thread_detail',
    ),
    path(
        '<int:pill_pk>/thread/<int:thread_pk>/update/',
        views.thread_update,
        name='thread_update',
    ),
    path(
        '<int:pill_pk>/thread/<int:thread_pk>/delete/',
        views.thread_delete,
        name='thread_delete',
    ),
    path(
        '<int:pill_pk>/thread/<int:thread_pk>/likes/',
        views.likes,
        name='likes',
    ),
     path(
        '<int:pill_pk>/comment/<int:thread_pk>/create/',
        views.create_comment,
        name='create_comment',
    ),
    path(
        '<int:pill_pk>/comment/<int:comment_pk>/delete/',
        views.delete_comment,
        name='delete_comment',
    ),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <title>Document</title>
    <style>
      .pill-card img {
        height: 300px;
        object-fit: cover;
      }
      .pill-card .card-title {
        font-size: 1rem;
        font-weight: 600;
      }
      .pill-card .card-text {
        font-size: 0.9rem;
        color: #666;
      }
      .pill-card .card-subtitle {
        font-size: 0.8rem;
        color: #999;
      }
      .pill-card .card-body {
        display: flex;
        flex-direction: column;
      }
      .pill-card .card-subtitle {
        margin-top: auto;
      }
    </style>
  </head>

  <body>
    <nav
      class="navbar bg-success navbar-expand-lg border-bottom border-body mb-4"
      data-bs-theme="dark"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pills:index' %}">ThRead</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto text-end mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href="{% url 'pills:index' %}"
                >INDEX</a
              >
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'accounts:profile' user.username %}"
                >MY PROFILE</a
              >
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input class="nav-link" type="submit" value="LOGOUT" />
              </form>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">{% block content %} {% endblock content %}</div>
    {% block script %}{% endblock script %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </body>
</html>